# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cloudfront"
  s.version = "1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Belkacem REBBOUH"]
  s.date = "2013-05-09"
  s.description = "A tested Cloudfront\u{2122} client, that handles all api actions on distributions and invalidations"
  s.email = "belkacem@rebbouh.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "cloudfront.gemspec",
    "lib/cloudfront.rb",
    "lib/cloudfront/connection.rb",
    "lib/cloudfront/distribution/distribution.rb",
    "lib/cloudfront/distribution/download_distribution.rb",
    "lib/cloudfront/distribution/streaming_distribution.rb",
    "lib/cloudfront/errors/cloudfront_error.rb",
    "lib/cloudfront/errors/cname_already_exists_error.rb",
    "lib/cloudfront/errors/distribution_already_exists_error.rb",
    "lib/cloudfront/errors/illegal_update_error.rb",
    "lib/cloudfront/errors/invalid_origin_access_identity_error.rb",
    "lib/cloudfront/errors/invalid_origin_error.rb",
    "lib/cloudfront/errors/invalid_required_protocol_error.rb",
    "lib/cloudfront/errors/missing_body_error.rb",
    "lib/cloudfront/errors/precondition_failed_error.rb",
    "lib/cloudfront/errors/too_many_distribution_cnames_error.rb",
    "lib/cloudfront/errors/too_many_distributions_error.rb",
    "lib/cloudfront/errors/too_many_trusted_signers_error.rb",
    "lib/cloudfront/errors/trusted_signer_does_not_exist_error.rb",
    "lib/cloudfront/exceptions/delete_enabled_distribution_exception.rb",
    "lib/cloudfront/exceptions/distribution_already_disabled_exception.rb",
    "lib/cloudfront/exceptions/distribution_already_enabled_exception.rb",
    "lib/cloudfront/exceptions/distribution_configuration_exception.rb",
    "lib/cloudfront/exceptions/missing_etag_exception.rb",
    "lib/cloudfront/helpers/aliases.rb",
    "lib/cloudfront/helpers/cache_behavior.rb",
    "lib/cloudfront/helpers/cache_behaviors.rb",
    "lib/cloudfront/helpers/download_distribution.rb",
    "lib/cloudfront/helpers/invalidation.rb",
    "lib/cloudfront/helpers/logging.rb",
    "lib/cloudfront/helpers/origin.rb",
    "lib/cloudfront/helpers/origin_access_identity.rb",
    "lib/cloudfront/helpers/origins.rb",
    "lib/cloudfront/helpers/s3_origin.rb",
    "lib/cloudfront/helpers/streaming_distribution.rb",
    "lib/cloudfront/helpers/trusted_signers.rb",
    "lib/cloudfront/invalidation/invalidations.rb",
    "lib/cloudfront/origin_access_identity/origin_access_identity.rb",
    "lib/cloudfront/utils/api.rb",
    "lib/cloudfront/utils/array.rb",
    "lib/cloudfront/utils/configuration_checker.rb",
    "lib/cloudfront/utils/string.rb",
    "lib/cloudfront/utils/util.rb",
    "lib/cloudfront/utils/xml_serializer.rb",
    "lib/faraday_middleware/request/cloudfront_signer.rb",
    "lib/faraday_middleware/request/xml_content_type.rb"
  ]
  s.homepage = "https://github.com/Belkacem/cloudfront"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A tested Cloudfront\u{2122} gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, [">= 0"])
      s.add_runtime_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_runtime_dependency(%q<multi_xml>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<vcr>, ["~> 1.11.3"])
      s.add_development_dependency(%q<webmock>, ["~> 1.7.0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
    else
      s.add_dependency(%q<faraday>, [">= 0"])
      s.add_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_dependency(%q<multi_xml>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<vcr>, ["~> 1.11.3"])
      s.add_dependency(%q<webmock>, ["~> 1.7.0"])
      s.add_dependency(%q<timecop>, [">= 0"])
    end
  else
    s.add_dependency(%q<faraday>, [">= 0"])
    s.add_dependency(%q<faraday_middleware>, [">= 0"])
    s.add_dependency(%q<multi_xml>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<vcr>, ["~> 1.11.3"])
    s.add_dependency(%q<webmock>, ["~> 1.7.0"])
    s.add_dependency(%q<timecop>, [">= 0"])
  end
end

